# This file has been temporarily disabled to fix workflow errors
#
# To re-enable Crowdin integration:
# 1. Add CROWDIN_PROJECT_ID to GitHub secrets
# 2. Add CROWDIN_PERSONAL_TOKEN to GitHub secrets
# 3. Restore the original configuration below
#
# Original configuration:
# project_id_env: CROWDIN_PROJECT_ID
# api_token_env: CROWDIN_PERSONAL_TOKEN
# base_path: .
# base_url: 'https://api.crowdin.com'
# preserve_hierarchy: true
# files:
#   - source: /src/locales/en.json
#     translation: '/src/locales/%two_letters_code%.json'
#     type: json
